[package]
name = "mips-emu-wasm"
version = "0.1.0"
edition = "2024"

[lib]
name = "mips_emu_wasm"
crate-type = ["rlib", "cdylib"] 

[dependencies]
wasm-bindgen = "0.2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde-wasm-bindgen = "0.6"